### ISSUE TITLE
Paste into the alda REPL 

### ISSUE THREAD

**Issue by sbandx** [alda-lang/alda-repl-clj#1]
It would be really great to just be able to paste a string of notes directly into the alda REPL command prompt window. Don't know if that's possible, depending on how it works?

**Comment by jgkamat** [comment]
@sbandx you should be able to do this right now, but this is dependent on your terminal, not alda itself. Being able to paste into your terminal _should_ paste into the alda repl if it is active as well. 

On most terminals I've tried, the shortcut is `ctrl-shift-v` to paste (and `ctrl-shift-c` to copy). What terminal are you using? I can try to look up the shortcuts/features for your terminal!

**Comment by sbandx** [comment]
You are correct.  This is the standard Windows 10 cmd.exe. You can actually just paste by right clicking on the mouse.
